// bugs/bugManifest.js

const BUG_MANIFEST = {
  'force-crash': 'Forces immediate hard breakdown execution path.',
  'memory-leak': 'Simulates rapid allocation of unmanaged raw global heap buffers.',
  'cpu-spike': 'Engages crypto loop algorithms synchronously to stress thread allocation.',
  'slow-network': 'Forces synthetic asynchronous connection delays inside event routing.',
  'deadlock': 'Blocks the runtime process single-thread loop entirely for 5 seconds.',
  'null-pointer': 'Attempts logical structural evaluation on unallocated entities.',
  'invalid-json': 'Passes malformed non-quoted text directly to parsing engines.',
  'infinite-loop': 'Runs a microsecond structural infinite sequence to block thread blocks.',
  'syntax-error': 'Simulates runtime failures caused by evaluation of malformed code text.',
  'type-coercion-bug': 'Triggers logic path failure through implicit conversions.',
  'dns-failure': 'Forces core domain-name protocol addressing failure lookups.',
  'fs-write-fail': 'Triggers local disk capacity write protection parameters.',
  'fs-read-fail': 'Attempts system lookups across unindexed hardware directories.',
  'port-conflict': 'Attempts redundant address initialization across bounded resources.',
  'ssl-expired': 'Simulates secure transport certificate date boundaries failures.',
  'cors-blocked': 'Simulates cross-origin gateway header origin parsing rejections.',
  'eval-error': 'Runs unsafe string evaluations inside isolated context structures.',
  'range-error': 'Passes variable sets beyond platform numeric restrictions.',
  'uri-error': 'Passes bad characters to standard address decoding components.',
  'event-emitter-leak': 'Registers endless asynchronous event hooks without clearing them.',
  'gc-freeze': 'Forces persistent data tracking structures to block clean routines.',
  'buffer-alloc-error': 'Attempts safe allocation of oversized uninitialized data structures.',
  'zlib-error': 'Passes raw uncompressed data streams to decompression filters.',
  'child-process-fail': 'Attempts child core forks with invalid environment access parameters.',
  'intl-error': 'Passes un-parsable formatting localization variables into translation engines.',
  'module-not-found': 'Simulates a lookup failure for a non-existent runtime dependency.',
  'array-bound-panic': 'Attempts operations on empty memory indices.',
  'async-deadlock': 'Creates two interdependent promises that wait infinitely.',
  'timer-overflow': 'Schedules event timers with values exceeding safe bounds.',
  'prototype-pollution': 'Simulates security warnings for base object overrides.',
  'crypto-fail': 'Simulates decryption cipher mismatch routines.',
  'http2-error': 'Simulates high-velocity HTTP/2 stream frame breakdown events.',
  'process-disconnect': 'Triggers internal child process abstraction disconnect alerts.',
  'worker-terminate': 'Abruptly kills asynchronous sub-thread processing contexts.',
  'async-hooks-leak': 'Leaks continuous execution reference graphs inside memory storage.',
  'v8-heap-exhaust': 'Forces an intentional low-level system memory pool allocation fault.',
  'readline-freeze': 'Locks interface text streams into perpetual polling states.',
  'repl-crash': 'Forces evaluation engine failures within specialized code contexts.',
  'stream-destroy': 'Closes processing streams before downstream operations complete.',
  'cluster-disconnect': 'Forces active cluster workers out of synchronization trees.',
  'net-server-fail': 'Simulates transport-level listener failures during operational initialization.',
  'dgram-error': 'Throws transmission errors within connectionless data channels.',
  'math-precision-error': 'Triggers float processing calculations that yield broken control values.',
  'aborted-fetch': 'Cancels internal platform data fetches midway through processing.',
  'auth-bypass': 'Triggers administrative verification bypass warnings.',
  'data-corruption': 'Injects raw non-standard multi-byte sequences into operational chunks.',
  'race-condition': 'Forces non-atomic asynchronous operations order conflicts.',
  'request-timeout': 'Stalls protocol synchronization parameters.',
  'db-fail': 'Simulates localized persistence layer connectivity loss.',
  'missing-env': 'Validates system dependencies against critical fallback constraints.',
  'permission-denied': 'Simulates system access failures on protected logical files.',
  'bad-padding': 'Throws padding errors during decryption of block ciphers.',
  'heap-buffer-overflow': 'Attempts memory copying that exceeds allocated boundaries.',
  'segmentation-fault': 'Triggers simulated access to unauthorized hardware memory frames.',
  'stack-underflow': 'Attempts extraction steps on empty stack registers.'
};

module.exports = { BUG_MANIFEST };
